### ISSUE TITLE
Roadmap v1.0.0+

### ISSUE THREAD

**Issue by ftrrtf** [ftrrtf/FtrrtfRollbarBundle#22]
It's a rough plan of what to do for the v1.0.0 release. 
If you have some suggestions or comments — you are welcome!

- [ ] PHP 5.5 as minimum version.
- [ ] Symfony 2.7 (2.8?) as minimum version
- [ ] Integration test
- [ ] NullLoger/DebugLogger for notifier
- [ ] Option to set up custom checkIgnore function
- [ ] Update docs
- [ ] ???

**Comment by ftrrtf** [comment]
cc @mplachta @filipgolonka @rafalkanski @wsromek @dincho

**Comment by filipgolonka** [comment]
looks good!

**Comment by dincho** [comment]
Well, SF 2.7 is LTS until mid 2018

Also:
- why would you need "NullLoger/DebugLogger" ?
- why would you need to bump PHP to 5.5, what features are you plan using?


I'd rush myself to get this bundle deployed to production ASAP and report any major issues before 1.0

**Comment by wsromek** [comment]
:+1: though since SF 2.7 requires PHP 5.3.9 I agree with dincho as to PHP version.

**Comment by ftrrtf** [comment]
@dincho Thank you for your questions.

> Well, SF 2.7 is LTS until mid 2018

2.8 is LTS until 2018 also. What's better?

---

> why would you need "NullLoger/DebugLogger" ?

Now to not send messages, for example in dev env, have to do something like this

```
if ($this->has('ftrrtf_rollbar.notifier')) {
    $this->get('ftrrtf_rollbar.notifier')->reportMessage("Some message");
}
```

Therefore, for the dev env would like to be able to ignore all the messages and not sent to the rollbar. Or send somewhere in logs (symfony logs, etc).

---

>why would you need to bump PHP to 5.5, what features are you plan using?

Looking at the minimum version of php for Symfony 2.7/2.8 — I chose 5.3.* first too. But then I researched several popular bundles, some statistics, and I changed my mind. 

For example, take a look https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json#L24

New symfony requries php >= 5.5.9
https://packagist.org/packages/symfony/symfony#v3.0.1

Also some statistics for 2015: https://seld.be/notes/php-versions-stats-2015-edition

And finally http://php.net/supported-versions.php
![image](https://cloud.githubusercontent.com/assets/424723/12575475/fa58fd56-c40c-11e5-840a-ed53197fa582.png)
PHP 5.3 is dead already. Who uses it? Even if someone else uses it — the old bundle version with the PHP 5.3 and Symfony 2.3-2.8 still here. 

Right now - there are no restrictions (on the syntax or features) to move to a new version of the language. But I do not want to limit themselves in the future because of this no one needs support (IMO) right now.

**Comment by dincho** [comment]
I'm aware of all versions and EOL dates.

But if you want to support sf 2.8, you should also support PHP 5.3, because of [symfony requirement](https://packagist.org/packages/symfony/symfony#v2.8.2), otherwise it does not make much sense with SF 2.8 + PHP 5.5.

I meant you should set requirement either:
- SF 2.8 + PHP 5.3
- SF 3.0 + PHP 5.5

However, I'm not convincing you to support legacy PHP&Symfony, just my 2c.
In general I'm :+1: for versions bump. This would allow, as you said, using new features without major version bump.

**Comment by dincho** [comment]
> if ($this->has('ftrrtf_rollbar.notifier')) {
>     $this->get('ftrrtf_rollbar.notifier')->reportMessage("Some message");
> }

I see. I never trough of this use case. I plan to use it only for exception reporting.

In this case it makes sense. I'd also suggest symfony WDT plugin as notifier.

**Comment by ftrrtf** [comment]
I guess requirement of php is not strict, and we can do it in the way like FOSRestBundle, which is MUCH more popular like my one, so I think we can trust their decision.

**Comment by ftrrtf** [comment]
What do we choose? 
I vote for Symfony 2.7/2.8 + PHP >= 5.5.9 (like in sf 3.0)

**Comment by dincho** [comment]
I'm OK with this.

**Comment by ftrrtf** [comment]
FYI: Master branch can be unstable now (in theory). Periodically I will be releasing almost stable tags (like 1.0.0-alpha/beta*). There is a big chance that there will be some interfaces or configuration changes, some rename refactoring. The priority for now — unit and integration tests, to be able to add more new features without fear to break old ones.
